time_periods:
  morning_rush:
    start: "07:00"
    end: "09:30"
    multiplier: 1.8
  
  lunch_peak:
    start: "11:30"
    end: "13:30"
    multiplier: 1.4
  
  evening_rush:
    start: "16:00"
    end: "18:30"
    multiplier: 2.0
  
  night_time:
    start: "22:00"
    end: "05:00"
    multiplier: 0.3

demand_types:
  rideshare:
    base_rate_per_hour: 40  # Average number of ride requests per hour
    service_types:
      - vehicle_type: "ev_sedan"
        percentage: 75
      - vehicle_type: "ev_suv"
        percentage: 25
    typical_trip_distance_km:
      min: 2
      max: 12
      mean: 4
      std_dev: 2
    
  food_delivery:
    base_rate_per_hour: 30  # Average number of delivery requests per hour
    service_types:
      - vehicle_type: "e_bike_courier"
        percentage: 70
      - vehicle_type: "ev_cargo_van"
        percentage: 30
    typical_trip_distance_km:
      min: 1
      max: 6
      mean: 2.5
      std_dev: 1.2

# Demand hotspots for Akron
demand_hotspots:
  downtown:
    center:
      lat: 41.0814
      lon: -81.5190
    radius_km: 1.0
    demand_multiplier: 1.6
    active_types: ["rideshare", "food_delivery"]
  
  university:
    center:
      lat: 41.0770
      lon: -81.5115
    radius_km: 0.8
    demand_multiplier: 1.5
    active_types: ["rideshare", "food_delivery"]
    
  fairlawn:
    center:
      lat: 41.1289
      lon: -81.6214
    radius_km: 1.2
    demand_multiplier: 1.3
    active_types: ["rideshare", "food_delivery"]
    
  chapel_hill:
    center:
      lat: 41.1283
      lon: -81.4701
    radius_km: 1.0
    demand_multiplier: 1.4
    active_types: ["rideshare", "food_delivery"] 