simulation:
  name: "san_francisco_ev_network"
  description: "Electric vehicle rideshare and delivery simulation for San Francisco"
  
  # Time settings
  duration_hours: 24
  time_step_seconds: 30
  start_time: "2024-01-15T00:00:00"
  
  # Geographic bounds
  city: "San Francisco, California"
  bounds:
    north: 37.8120
    south: 37.7070
    east: -122.3516
    west: -122.5153
  
  # Configuration files
  config_files:
    vehicle_types: "config/examples/vehicle_types.yaml"
    charging_infrastructure: "config/examples/charging_infrastructure.yaml"
    demand_patterns: "config/examples/demand_patterns.yaml"
  
  # Initial fleet configuration
  initial_fleet:
    ev_sedan: 100
    ev_suv: 50
    ev_cargo_van: 30
    e_bike_courier: 80
  
  # Simulation features
  enable_features:
    battery_degradation: true
    weather_effects: true
    traffic_conditions: true
    dynamic_pricing: true
    predictive_charging: true
  
  # Optimization parameters
  optimization:
    rebalancing:
      enabled: true
      interval_minutes: 15
      max_idle_time_minutes: 30
    
    charging_strategy:
      type: "predictive"  # Options: basic, predictive, opportunistic
      min_battery_level: 0.15
      target_battery_level: 0.90
    
    matching_algorithm:
      type: "weighted_bipartite"  # Options: nearest, weighted_bipartite
      max_waiting_time_minutes: 10
      max_pickup_distance_km: 3
  
  # Logging and output
  logging:
    level: "INFO"
    metrics_interval_seconds: 60
    save_path: "output/logs"
  
  visualization:
    real_time: true
    save_snapshots: true
    snapshot_interval_minutes: 15
    save_path: "output/visualizations" 