fleet:
  fleet_size: 1000
  battery_capacity: 75
  average_miles_per_kwh: 4
  utilization: 1.8
  trip_distance_range: [2, 10]

charging_infrastructure:
  charging_depots: 1
  chargers_per_depot: 20
  charging_types:
    - type: "Level 3"
      power: 250
      time_to_80_percent: [15, 20]

simulation:
  simulation_duration: 86400  # 24 hours in seconds
  time_step: 1
